spring.config.import=optional:file:./.env[.properties]

spring.application.name=auth-service
server.port=${AUTH_PORT:5001}

spring.data.mongodb.uri=${DB_AUTH_URI}
spring.data.mongodb.database=${DB_AUTH_NAME}

jwt.secret=${JWT_SECRET}
jwt.expiration=604800000