spring.config.import=optional:file:./.env[.properties]

spring.application.name=device-service
server.port=${DEVICE_PORT:5006}

spring.data.mongodb.uri=${DB_DEVICE_URI}
spring.data.mongodb.database=${DB_DEVICE_NAME}

spring.data.mongodb.auto-index-creation=true

jwt.secret=${JWT_SECRET}