spring.config.import=optional:file:./.env[.properties]

spring.application.name=users-service
server.port=${USER_PORT:5005}

spring.data.mongodb.uri=${DB_USER_URI}
spring.data.mongodb.database=${DB_USER_NAME}

spring.data.mongodb.auto-index-creation=true

jwt.secret=${JWT_SECRET}